### ISSUE TITLE
Animations being broken

### ISSUE THREAD

**Issue by g8mz** [studioNOKOI/fnfoffsethelper#6]
i did everything correctly but everytime i build it, all animations are just one frame for the one of the dow animations (and yes if youre asking im using a bf spritesheet and would also know if theres any way to rotate thru offsets.)

**Comment by studioNOKOI** [comment]
this is too vague. closing for now. if you can describe it in more detail you should reopen this.

**Comment by g8mz** [comment]
> this is too vague. closing for now. if you can describe it in more detail you should reopen this.

understandable have a great day.

**Comment by Jotaro-Gaming** [comment]
> this is too vague. closing for now. if you can describe it in more detail you should reopen this.

.............................................................. if a maintainer (like you) closes an issue only a maintainer can open it again.
