### ISSUE TITLE
Legs of dad/bf off screen. Also it's a black screen and won't work now

### ISSUE THREAD

**Issue by ghost** [studioNOKOI/fnfoffsethelper#8]
So, I downloaded this thing and then I compile it...... but no matter what I do dad's feet are cut off and so are bfs.... the problem is that I need their feet because I need to align it with that like the tutorial you made said. I tried changing the resolution on the code and making it full screen but all it does is make things bigger and still cut off the dads feet. Don't know if my computer type isn't supported or something. I am on windows if that changes anything. So practically their feet always cuts off the window. Thank you for taking your time to read this.

**Comment by ghost** [comment]
I just realized that I should clarify better. Their feet aren't cut off.... they just go off screen and no matter what they stay that way even when resolution is changed. EDIT: And yes I tried "lime test html5" and "lime test windows" But it still doesn't work.     I even tried changing it from landscape to portrait in code and my computer..... and it still didn't work. Oh and heres a picture too. Its the same thing when I'm not in the browser version btw. EDIT 2: It's gotten worse.... now the application won't open it's just a black screen and closes itself. It started happening when I uninstalled it and reinstalled it again. (Maybe I'm missing a file or maybe a update did it... don't know) Sorry, if this is all too much for you at once. EDIT 3: I have tried everything I can.... but now the application is just a black screen. I compile it and it starts as a black screen and closes itself. I have all the files that came to the download and I'm not even modifying the code or files.... but it's still a black screen.
![fnf offset helper - Google Chrome 6_21_2021 6_38_11 PM](https://user-images.githubusercontent.com/86265921/122840331-e0fe0200-d2c7-11eb-97d1-2112943b790c.png)

**Comment by AbnormalPoof** [comment]
it's the window size, just zoom out

**Comment by ghost** [comment]
> it's the window size, just zoom out

Nope have tried that too. Same thing... also its just a black screen so it wouldn't matter anyway. Thanks for trying to help. It's fine tho new kade engine has a stage debug so I can use that. Again, thank you for trying to help.
